package proxy

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// What versola-cli wrote before UpstreamsFile: the upstream blocks inline,
// CRLF line endings (the template files are CRLF), local's resolver line.
func legacyConf(local bool) string {
	var b strings.Builder
	b.WriteString("# Generated by versola-cli (`versola configure`) -- rewritten on every\r\n# configure, don't edit by hand.\r\n\r\n")
	b.WriteString("# auth/edge: on the host's loopback (vps, network_mode: host) or by\r\n# compose service name (local, bridge network).\r\n")
	if local {
		b.WriteString("resolver 127.0.0.11 valid=10s ipv6=off;\r\n")
		b.WriteString("upstream auth_backend {\r\n    zone auth_backend 64k;\r\n    server auth:8080 resolve;\r\n    keepalive 32;\r\n}\r\n\r\n")
		b.WriteString("upstream edge_backend {\r\n    zone edge_backend 64k;\r\n    server edge:8095 resolve;\r\n    keepalive 32;\r\n}\r\n\r\n")
	} else {
		b.WriteString("upstream auth_backend {\r\n    server 127.0.0.1:8080;\r\n    keepalive 32;\r\n}\r\n\r\n")
		b.WriteString("upstream edge_backend {\r\n    server 127.0.0.1:8095;\r\n    keepalive 32;\r\n}\r\n\r\n")
	}
	b.WriteString("map $http_host $versola_host {\r\n    \"\"      $host;\r\n    default $http_host;\r\n}\r\n\r\n")
	b.WriteString("server {\r\n    listen 80;\r\n    location / { proxy_pass http://auth_backend; }\r\n}\r\n")
	return b.String()
}

func legacyBundle(t *testing.T, local bool) string {
	t.Helper()
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "proxy/conf.d"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, versolaConfFile), []byte(legacyConf(local)), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

func TestMigrateLegacyUpstreams(t *testing.T) {
	for _, local := range []bool{false, true} {
		mode := ModeNginx
		auth, edge := []Backend{{Service: "auth", Port: 8080}}, []Backend{{Service: "edge", Port: 8095}}
		if local {
			mode = ModeLocal
		}
		dir := legacyBundle(t, local)
		cfg := Config{Mode: mode, Auth: auth, Edge: edge}
		done, err := MigrateLegacyUpstreams(dir, cfg, nil)
		if err != nil || !done {
			t.Fatalf("local=%v: %v, %v", local, done, err)
		}
		conf, _ := os.ReadFile(filepath.Join(dir, versolaConfFile))
		up, _ := os.ReadFile(filepath.Join(dir, UpstreamsFile))
		if anyUpstreamBlock.Match(conf) || strings.Contains(string(conf), "resolver 127.0.0.11") {
			t.Errorf("local=%v: versola.conf still has upstreams or the resolver:\n%s", local, conf)
		}
		// The rest is untouched.
		for _, keep := range []string{"map $http_host $versola_host", "proxy_pass http://auth_backend;", "listen 80;"} {
			if !strings.Contains(string(conf), keep) {
				t.Errorf("local=%v: versola.conf lost %q", local, keep)
			}
		}
		for _, want := range []string{"upstream auth_backend {", "upstream edge_backend {", "least_conn;"} {
			if !strings.Contains(string(up), want) {
				t.Errorf("local=%v: upstreams.conf lacks %q", local, want)
			}
		}
		if local != strings.Contains(string(up), "resolver 127.0.0.11") {
			t.Errorf("local=%v: the resolver belongs to upstreams.conf on local only", local)
		}
		// Idempotent: the current layout is left alone.
		if again, err := MigrateLegacyUpstreams(dir, cfg, nil); again || err != nil {
			t.Errorf("second run: %v, %v", again, err)
		}
	}
}

func TestMigrateLegacyUpstreamsPutsBackWhenNginxRejects(t *testing.T) {
	dir := legacyBundle(t, false)
	cfg := Config{Mode: ModeNginx, Auth: []Backend{{Service: "auth", Port: 8080}}, Edge: []Backend{{Service: "edge", Port: 8095}}}
	done, err := MigrateLegacyUpstreams(dir, cfg, func() error { return errors.New("bad") })
	if done || err == nil || !strings.Contains(err.Error(), "put back") {
		t.Fatalf("%v, %v", done, err)
	}
	conf, _ := os.ReadFile(filepath.Join(dir, versolaConfFile))
	if string(conf) != legacyConf(false) || HasUpstreamsFile(dir) {
		t.Errorf("not restored: upstreams file %v", HasUpstreamsFile(dir))
	}
}

func TestMigrateLegacyUpstreamsRefusesWhatItDoesNotRecognize(t *testing.T) {
	dir := legacyBundle(t, false)
	p := filepath.Join(dir, versolaConfFile)
	// A third upstream block someone added by hand.
	if err := os.WriteFile(p, []byte(legacyConf(false)+"upstream extra {\n    server 1.2.3.4;\n}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg := Config{Mode: ModeNginx, Auth: []Backend{{Service: "auth", Port: 8080}}, Edge: []Backend{{Service: "edge", Port: 8095}}}
	if done, err := MigrateLegacyUpstreams(dir, cfg, nil); done || err == nil {
		t.Errorf("%v, %v", done, err)
	}
	if HasUpstreamsFile(dir) {
		t.Error("wrote the upstreams file anyway")
	}
	// No upstream blocks at all.
	if err := os.WriteFile(p, []byte("server { listen 80; }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if done, err := MigrateLegacyUpstreams(dir, cfg, nil); done || err == nil {
		t.Errorf("%v, %v", done, err)
	}
}

// A migration that died between its two writes leaves both files defining
// the upstreams: running it again finishes it.
func TestMigrateLegacyUpstreamsFinishesAnInterruptedOne(t *testing.T) {
	dir := legacyBundle(t, false)
	if err := os.WriteFile(filepath.Join(dir, UpstreamsFile), []byte("upstream auth_backend { server 127.0.0.1:8080; }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	c := Config{Mode: ModeNginx, Auth: []Backend{{Service: "auth", Port: 8080}}, Edge: []Backend{{Service: "edge", Port: 8095}}}
	did, err := MigrateLegacyUpstreams(dir, c, nil)
	if err != nil || !did {
		t.Fatalf("did=%v err=%v", did, err)
	}
	conf, _ := os.ReadFile(filepath.Join(dir, versolaConfFile))
	if anyUpstreamBlock.Match(conf) {
		t.Errorf("upstreams still inline:\n%s", conf)
	}
	if did, err := MigrateLegacyUpstreams(dir, c, nil); err != nil || did {
		t.Errorf("second run: did=%v err=%v", did, err)
	}
}

// The resolver line is the one local's old template wrote, however it was
// indented; anything else naming 127.0.0.11 is not ours to remove.
func TestLegacyResolverLineVariants(t *testing.T) {
	for _, line := range []string{
		"resolver 127.0.0.11 valid=10s ipv6=off;\r\n",
		"  resolver 127.0.0.11  valid=10s ipv6=off;\n",
	} {
		if !legacyResolverLine.MatchString(line) {
			t.Errorf("not matched: %q", line)
		}
	}
	for _, line := range []string{
		"resolver 8.8.8.8 1.1.1.1 ipv6=off;\n",
		"resolver 127.0.0.11 8.8.8.8 ipv6=off;\n",
		"resolver 127.0.0.11;\n",
	} {
		if legacyResolverLine.MatchString(line) {
			t.Errorf("matched: %q", line)
		}
	}
}

// nginx mode: the TLS resolver stays even when the host's list starts with
// 127.0.0.11 -- only local's upstreams.conf has a resolver of its own.
func TestMigrateKeepsATlsResolverThatNamesDockerDns(t *testing.T) {
	dir := legacyBundle(t, false)
	confPath := filepath.Join(dir, versolaConfFile)
	b, _ := os.ReadFile(confPath)
	tls := "resolver 127.0.0.11 valid=10s ipv6=off;\r\n"
	if err := os.WriteFile(confPath, append([]byte(tls), b...), 0o644); err != nil {
		t.Fatal(err)
	}
	c := Config{Mode: ModeNginx, Auth: []Backend{{Service: "auth", Port: 8080}}, Edge: []Backend{{Service: "edge", Port: 8095}}}
	if _, err := MigrateLegacyUpstreams(dir, c, nil); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(confPath)
	if !strings.Contains(string(got), "resolver 127.0.0.11") {
		t.Errorf("the resolver was removed:\n%s", got)
	}
}

// A closing brace that is indented or followed by a comment still ends the
// block: what follows it (the map, the servers) is never cut out with it.
func TestMigrateStopsAtTheBlocksOwnBrace(t *testing.T) {
	for name, closing := range map[string]string{"indented": "    }\r\n", "comment": "} # edge\r\n"} {
		t.Run(name, func(t *testing.T) {
			dir := legacyBundle(t, false)
			confPath := filepath.Join(dir, versolaConfFile)
			b, _ := os.ReadFile(confPath)
			edited := strings.Replace(string(b), "server 127.0.0.1:8095;\r\n    keepalive 32;\r\n}\r\n", "server 127.0.0.1:8095;\r\n    keepalive 32;\r\n"+closing, 1)
			if edited == string(b) {
				t.Fatal("fixture not edited")
			}
			if err := os.WriteFile(confPath, []byte(edited), 0o644); err != nil {
				t.Fatal(err)
			}
			c := Config{Mode: ModeNginx, Auth: []Backend{{Service: "auth", Port: 8080}}, Edge: []Backend{{Service: "edge", Port: 8095}}}
			if _, err := MigrateLegacyUpstreams(dir, c, nil); err != nil {
				t.Fatal(err)
			}
			got, _ := os.ReadFile(confPath)
			for _, want := range []string{"map $http_host $versola_host", "proxy_pass http://auth_backend"} {
				if !strings.Contains(string(got), want) {
					t.Errorf("%q was cut out:\n%s", want, got)
				}
			}
			if anyUpstreamBlock.Match(got) {
				t.Errorf("upstream left:\n%s", got)
			}
		})
	}
}
