package deploy

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/versolauth/versola-cli/internal/fsutil"
	"github.com/versolauth/versola-cli/internal/state"
	"github.com/versolauth/versola-cli/internal/topology"
)

// replicasYAML renders replicas.yml: one compose service for each replica
// beyond slot 1 (auth-2, edge-3, ...), written next to compose.yml.
//
// A replica is its base service with only what makes it a separate replica
// changed: `extends` takes everything else -- image, env_file, volumes,
// depends_on -- from versola-tools' own service, so nothing is copied here
// and no secret reaches this file (a `docker compose config` copy would
// inline the env_file values). What differs is the container name, the
// listener variables, and the published ports, all shifted by the slot
// (see topology.Service.ForSlot). `!override` makes ports replace the base
// service's instead of being added to them, which would publish the base's
// host ports twice.
//
// Nothing is written for a deployment with one replica of each service; the
// bool says whether there is anything to write.
func replicasYAML(composeFile string, groups ...[]replica) ([]byte, bool, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by versola-cli (`versola up`) -- rewritten on every up,\n")
	buf.WriteString("# don't edit by hand. The replicas of auth and edge beyond the first, each\n")
	buf.WriteString("# its base service with a container name, ports and listener variables of\n")
	buf.WriteString("# its own.\n\nservices:\n")
	any := false
	for _, group := range groups {
		for _, r := range group {
			if r.Slot <= 1 {
				continue
			}
			any = true
			if err := writeReplica(&buf, composeFile, r); err != nil {
				return nil, false, err
			}
		}
	}
	return buf.Bytes(), any, nil
}

// quote is s as a YAML double-quoted scalar (JSON strings are YAML's).
func quote(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

func writeReplica(buf *bytes.Buffer, composeFile string, r replica) error {
	if !serviceNameOK(r.Service) || !serviceNameOK(r.Base) {
		return fmt.Errorf("%s: not a name compose accepts", r.Service)
	}
	fmt.Fprintf(buf, "  %s:\n    extends:\n      file: %s\n      service: %s\n", r.Service, quote(composeFile), r.Base)
	if name := topology.SlotContainerName(r.Ports.ContainerName(), r.Slot); name != "" {
		fmt.Fprintf(buf, "    container_name: %s\n", quote(name))
	}
	buf.WriteString("    environment:\n")
	for _, l := range r.listeners() {
		fmt.Fprintf(buf, "      %s: %s\n", l.Name, quote(strconv.Itoa(l.Port)))
	}
	if r.Ports.HostNetwork() {
		return nil // the host's own ports; `network_mode: host` comes from the base
	}
	if err := checkReplicable(r); err != nil {
		return err
	}
	pubs, unfixed := r.Ports.Publications(), r.Ports.UnfixedPorts()
	if len(pubs) == 0 && len(unfixed) == 0 {
		buf.WriteString("    ports: !override []\n")
		return nil
	}
	buf.WriteString("    ports: !override\n")
	for _, p := range pubs {
		fmt.Fprintf(buf, "      - target: %d\n        published: %s\n", p.Target, quote(p.Binding.PortString()))
		if p.HostIP != "" {
			fmt.Fprintf(buf, "        host_ip: %s\n", quote(p.HostIP))
		}
		buf.WriteString("        protocol: tcp\n")
	}
	for i, t := range unfixed {
		fmt.Fprintf(buf, "      - target: %d\n", t)
		if ip := r.Ports.UnfixedHostIP(i); ip != "" {
			fmt.Fprintf(buf, "        host_ip: %s\n", quote(ip))
		}
		buf.WriteString("        protocol: tcp\n")
	}
	return nil
}

// checkReplicable refuses a replica whose base service publishes something
// replicas.yml cannot carry over (UDP, a port range as the container port):
// the replica would start without it, silently.
func checkReplicable(r replica) error {
	if sk := r.Ports.Skipped(); len(sk) > 0 {
		return fmt.Errorf("%s publishes %s, which a replica cannot copy (only single TCP ports) -- remove it from the compose file's `ports:`, or do not run more than one %s", r.Base, strings.Join(sk, ", "), r.Base)
	}
	return nil
}

// serviceNameOK: what a compose service name may be, which also keeps a
// name from carrying YAML into the file.
func serviceNameOK(s string) bool {
	if s == "" {
		return false
	}
	for i, c := range s {
		ok := c >= 'a' && c <= 'z' || c >= '0' && c <= '9' || (i > 0 && (c == '_' || c == '.' || c == '-'))
		if !ok {
			return false
		}
	}
	return true
}

// writeReplicasFile writes replicas.yml into the bundle dir, or removes a
// stale one when there are no replicas beyond slot 1 any more (so the file
// never names services that are not meant to run).
func writeReplicasFile(dir, composeFile string, groups ...[]replica) error {
	content, any, err := replicasYAML(composeFile, groups...)
	if err != nil {
		return err
	}
	path := filepath.Join(dir, state.ReplicasFile)
	if !any {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("couldn't remove %s: %w", path, err)
		}
		return nil
	}
	if err := fsutil.WriteFileAtomic(path, content, 0o644); err != nil {
		return fmt.Errorf("couldn't write %s: %w", path, err)
	}
	return nil
}
